In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('income_evaluation.csv')
df.head()

age         workclass  fnlwgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital-gain  capital-loss  hours-per-week native-country income  
0          2174             0              40  United-States  <=50K  
1             0             0              13  United-States  <=50K  
2             0             0              40  United-States  <=50K  
3             0             0              40  United-States  <=50K  
4             0             0              40           Cuba  <=50K

In [4]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [5]:
df['income'].value_counts()

<=50K    24720
>50K      7841
Name: income, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('income', axis=1), df['income'],
                                                   test_size=0.2, random_state=0)

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
le = LabelEncoder()

In [11]:
le.fit(y_train)

LabelEncoder()

In [12]:
le.classes_

array(['<=50K', '>50K'], dtype=object)

In [13]:
y_train

15282    <=50K
24870    <=50K
18822    <=50K
26404    <=50K
7842     <=50K
         ...  
13123     >50K
19648    <=50K
9845     <=50K
10799     >50K
2732     <=50K
Name: income, Length: 26048, dtype: object

In [15]:
le.transform(y_train)

array([0, 0, 0, ..., 0, 1, 0])

In [16]:
pd.Series(le.transform(y_train))

0        0
1        0
2        0
3        0
4        0
        ..
26043    1
26044    0
26045    0
26046    1
26047    0
Length: 26048, dtype: int32

In [17]:
le.transform(y_test)

array([0, 0, 0, ..., 1, 0, 1])

In [18]:
len(df['native-country'].unique())

42

In [20]:
X_train['native-country']

15282    United-States
24870    United-States
18822    United-States
26404    United-States
7842     United-States
             ...      
13123    United-States
19648    United-States
9845     United-States
10799    United-States
2732     United-States
Name: native-country, Length: 26048, dtype: object

In [21]:
le1 = LabelEncoder()
le1.fit_transform(X_train['native-country'])

array([39, 39, 39, ..., 39, 39, 39])

In [22]:
label=pd.Series(le1.fit_transform(X_train['native-country']))

In [23]:
df['label']=label

In [24]:
df.head()

age         workclass  fnlwgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital-gain  capital-loss  hours-per-week native-country income  label  
0          2174             0              40  United-States  <=50K   39.0  
1             0             0              13  United-States  <=50K   39.0  
2             0             0              40  United-States  <=50K   39.0  
3             0             0              40  United-States  <=50K   39.0  
4             0             0              40           Cuba  <=50K   39.0